### PR TITLE
 perf: use accurate sleep timing with perf_counter

### LINKED ISSUE #1: perf: use accurate sleep timing mechanism
https://github.com/lloydlobo/keystrokes/blob/ac42dfb176a64f5d8aee99bfd95d7c9715bc4435/src/app.py#L229

Instead of using time.sleep() for the animation delay, we can utilize a more accurate timing mechanism, such as the time.perf_counter() function.

This function provides a higher resolution timer, allowing for more precise frame timing. 

Replace the sleep(curr_time + FRAME_DELAY - time()) line with the following code:

```
from time import perf_counter

elapsed_time = perf_counter() - curr_time
remaining_time = FRAME_DELAY - elapsed_time
if remaining_time > 0:
    sleep(remaining_time)

```

OR without perf_counter:

```
elapsed_time = time() - curr_time
if elapsed_time < FRAME_DELAY:
    sleep_time = FRAME_DELAY - elapsed_time
    sleep(sleep_time)
```

### PR DESCRIPTION
**Pull request by Harshal662**
added the following code

elapsed_time = time() - curr_time
if elapsed_time < FRAME_DELAY:
    sleep_time = FRAME_DELAY - elapsed_time
    sleep(sleep_time)

### CODE REVIEW

**Comment by lloydlobo** [comment]
Hey there, great job on your first contribution to this project! I noticed that your change significantly improved the smoothness of the animations. In relation to the original [issue](https://github.com/lloydlobo/keystrokes/issues/1#issue-1744938083), I wanted to suggest an additional enhancement. Would you be interested in refactoring the timing function to utilize `perf_counter()` instead of `time()`?

I took the liberty of trying out your pull request on my local machine, and when I replaced all instances of `time()` within the while loop with `perf_counter()`, the performance felt even better. Additionally, `perf_counter()` has a smaller footprint compared to `time()`. Let me know what you think about this suggestion. Keep up the great work!

**Comment by Harshal662** [comment]
Happy to help

**Comment by lloydlobo** [comment]
> Happy to help

Thanks for being open to the suggestion! Could you please confirm if you'll be making further changes to implement the suggestion? Feel free to reach out if you have any questions or need help with the changes. I'm here to assist you throughout the process.

Once again, I really appreciate your willingness to contribute, and I'm looking forward to seeing the updated implementation. Keep up the good work!

**Comment by Harshal662** [comment]
I will try to implement that

**Comment by Harshal662** [comment]
plz check

**Comment by lloydlobo** [comment]
> I will try to implement that

Thanks!

**Review by lloydlobo — APPROVED** [review]

**Pull request merged**
